---
# Circuit parameters for two fluxonia coupled via a transmon
# Parameters taken from Setiawan et. al. 2022 in the literature folder
# All quantities in GHz unless otherwise indicated
A: # Fluxonium A Parameters
 E_C: 1.8
 E_J: 4.5
 E_L: 1.5
 phi_ext: 0.5
 w: 11.24690169985146
B: # Fluxonium B Parameters
 E_C: 1.1
 E_J: 3.5
 E_L: 1.0
 phi_ext: 0.5
 w: 5.403539364174444
C: # Transmon Coupler Parameters
 U: 0.005
 w: 6.974335690969341
